version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./ .dockerenv
    environment:
      - MYSQLDB_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQL_DATABASE
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: vedant2040/back-api
    restart: unless-stopped
    env_file: ./ .dockerenv
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=$MYSQL_DATABASE
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_NAME=$MYSQL_NAME
      - DB_CONNECTION_LIMIT=$MYSQL_CONNECTION_LIMIT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

volumes:
  db:


